services:

  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8082:8082"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongo
      
  backend:
    image: pedrodinis/movies-backend:latest
    container_name: movies-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/moviesdb

  frontend:
    image: pedrodinis/movies-frontend:latest
    container_name: movies-frontend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - backend

volumes:
  mongo_data: